# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  wp-dev.ninghao.net:
    site_hosts:
      - canonical: wp-dev.ninghao.net
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: wanghao@ninghao.net
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
